### ISSUE TITLE
Count distinct abnormal tasks size is wrong due to limit ES aggs buckets size to 10000.

### ISSUE THREAD

**Issue by liusenhua** [cubefs/compass#100]
The issue is in portal report service.
com.oppo.cloud.portal.service.impl.ReportServiceImpl.getStaticsDataByReportData()

**Comment by liusenhua** [comment]
should  use ES cardinality algorithm to count distinct value

**Comment by zebozhuang** [comment]
> should use ES cardinality algorithm to count distinct value

Got it, the origin code is implemented by script to realize the statistic and it is limited by the agg bucket 1000
```
AggregationBuilder aggregationBuilderAbnormalJobCount =
                AggregationBuilders.terms("groupByCount")
                        .script(new Script("doc['projectName.keyword'].value+'@@'+doc['flowName.keyword'].value+'@@'+doc['taskName.keyword'].value")
                        ).size(10000);
```
Good feedback[thumbs up]

By the way, could you offer the pr for this bug if you have tested it when you are convenient.
