### ISSUE TITLE
[Feature]: Docker Compose based one-click Playground

### ISSUE THREAD

**Issue by wForget** [cubefs/compass#124]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Is your feature request related to a problem? Please describe.

We can refer to https://github.com/apache/kyuubi/issues/2365 to implement a one-stop compass playground based on docker, which helps users quickly experience compass.

**Comment by zebozhuang** [comment]
> ### Contact Details
> _No response_
> 
> ### Is there an existing issue for this?
> * [x]  I have searched all the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> We can refer to [apache/kyuubi#2365](https://github.com/apache/kyuubi/issues/2365) to implement a one-stop compass playground based on docker, which helps users quickly experience compass.
> 
> ### Describe the solution you'd like.
> _No response_
> 
> ### Describe an alternate solution.
> _No response_
> 
> ### Anything else? (Additional Context)
> _No response_

@wForget Hi, is there any problem if we use compose?

**Comment by wForget** [comment]
> Hi, is there any problem if we use compose?

I have completed the compass dependent components in the Playground based on Docker Compose. Due to development machine resource constraints, it is difficult to add compass services. I will submit a WIP PR first later.

**Comment by zebozhuang** [comment]
> > Hi, is there any problem if we use compose?
> 
> I have completed the compass dependent components in the Playground based on Docker Compose. Due to development machine resource constraints, it is difficult to add compass services. I will submit a WIP PR first later.

Nice
