### ISSUE TITLE
[Question]: 日志路径解析的，为什么会出现_log结尾呢

### ISSUE THREAD

**Issue by cn-tingguo** [cubefs/compass#126]
### What would you like to ask or discuss?

![image](https://github.com/cubefs/compass/assets/20660223/9ba462f5-27e5-4815-b5ea-774c0ec45ffd)

**Comment by cn-tingguo** [comment]
正常情况hdfs日志应该是 /data/ds2hdfs/dolphinscheduler/2023-09-22/4292/1149520/3552154.log 这个格式

**Comment by zebozhuang** [comment]
> 正常情况hdfs日志应该是 /data/ds2hdfs/dolphinscheduler/2023-09-22/4292/1149520/3552154.log 这个格式

是因为日志格式 `1149520/3552154.log` 有带 .（dot）号，我们这边解析escape了，查看一下，
[https://github.com/cubefs/compass/blob/main/task-application/src/main/java/com/oppo/cloud/application/util/EscapePathUtil.java#L26](url)

```
    public static String escape(String str) {
        if (str != null) {
            return str.replaceAll("\\s+|:|\\.+|~", "_");
        }
        return null;
    }
```

**Comment by cn-tingguo** [comment]
所以这个是正常的逻辑处理吗？

**Comment by zebozhuang** [comment]
> 所以这个是正常的逻辑处理吗？

之前我们使用flume上传日志，发现`:`有异常，替换为下划线了，如果不使用flume可以改下，但奇怪都是dot也需要替换，我们再确认下，你可以先去掉看看

**Comment by zebozhuang** [comment]
> 所以这个是正常的逻辑处理吗？

@cn-tingguo 这里有个hadoop文件合理标准，可以看下
[https://hadoop.apache.org/docs/r3.2.2/hadoop-project-dist/hadoop-common/filesystem/model.html#File_references](url)

**Comment by cn-tingguo** [comment]
但是我通过flume上传目录的时候是这种格式，hdfs 版本是2.6。 
![image](https://github.com/cubefs/compass/assets/20660223/0539c763-b7d0-4fc9-8245-4aa5931d8318)

我注释掉住特殊字符转移的代码后还是会提示_log 路径不存在，是还有在其他抵挡校验吗

**Comment by zebozhuang** [comment]
> 但是我通过flume上传目录的时候是这种格式，hdfs 版本是2.6。 ![image](https://user-images.githubusercontent.com/20660223/269857533-0539c763-b7d0-4fc9-8245-4aa5931d8318.png)
> 
> 我注释掉住特殊字符转移的代码后还是会提示_log 路径不存在，是还有在其他代码中校验吗



不应该，你clean下，另外使用新的数据看看， 只要改`return str.replaceAll("\\s+|:|\\.+|~", "_");`

**Comment by cn-tingguo** [comment]
修改代码 return str.replaceAll("\\s+|:|~", "_"); 重新编译，目前正常获取日志路径

**Comment by zebozhuang** [comment]
good, nice!


| |
zhuangzebo
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年9月22日 17:04 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cubefs/compass] [Question]: 日志路径解析的，为什么会出现_log结尾呢 (Issue #126) |

修改代码 return str.replaceAll("\s+|:|~", "_"); 重新编译，目前正常获取日志路径
