### ISSUE TITLE
[Bug]: Too many files open issue caused by fs/fsDataInputStream  is not closed if exception occurs

### ISSUE THREAD

**Issue by liusenhua** [cubefs/compass#130]
### Contact Details

senhua.liu@gmail.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Current Behavior

1. Compass will throw "too many files open" exception after running long time
2. use lsof to locate fd,  found task-parser occupy 600000+ connection

**Comment by zebozhuang** [comment]
> All parsers have below wrong code pattern for closing file:
> 
> ```
> public void replay(ReaderObject readerObject) throws Exception {
>     while (true) {
>         String line;
>         try {
>             line = readerObject.getBufferedReader().readLine();
>         } catch (IOException e) {
>             log.error(e.getMessage());
>             break;
>         }
>         if (line == null) {
>             break;
>         }
>         parseLine(line);
>     }
>     if (readerObject.getFs() != null) {
>         readerObject.getFs().close();
>     }
>     this.correlate();
> }
> ```
Nice fix. Close it #131
