### ISSUE TITLE
[Question]: Question about docker-compose way to run compass want to monitor local spark on yarn

### ISSUE THREAD

**Issue by liewkaitsan** [cubefs/compass#179]
Contact Details
No response

What would you like to ask or discuss?
if you use docker-compose start compass how to connect to my local hadoop and spark it, my local hdfs is a pseudo-cluster mode, yarn is the default configuration, spark running on the yarn cluster, the version number is: spark3.3.1, hadoop3.2.3
The configuration file is as follows
hdfs-site.xml
```
<configuration>
  <property>
    <name>dfs.replication</name>
    <value>2</value>
  </property>
  <property>
  <name>dfs.namenode.name.dir</name>
  <value>/Users/kaitsan/data/hadoop/hdfs/namenode</value>
  </property>
  <property>
  <name>dfs.datanode.data.dir</name>
  <value>/Users/kaitsan/data/hadoop/hdfs/datanode</value>
  </property>
</configuration>
```
core-site.xml
```
<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://localhost:9000</value>
  </property>
    <property>
        <name>hadoop.proxyuser.kaitsan.hosts</name>
        <value>*</value>
    </property>
    <property>
        <name>hadoop.proxyuser.kaitsan.groups</name>
        <value>*</value>
    </property>
</configuration>
```
mapred-site.xml

```
<configuration>
    <property>
         <name>mapreduce.framework.name</name>
         <value>yarn</value>
     </property>
   <property>
         <name>mapreduce.map.java.opts</name>
         <value>-Xmx1024m</value>
     </property>
   <property>
         <name>mapreduce.reduce.java.opts</name>
         <value>-Xmx1024m</value>
     </property>
    <property>
        <name>mapreduce.jobhistory.address</name>
        <value>localhost:10020</value>
    </property>
    <property>
        <name>mapreduce.jobhistory.webapp.address</name>
        <value>localhost:19888</value>
    </property>
</configuration>
```
yarn-site.xml
```
<configuration>

    <property>
        <name>yarn.nodemanager.aux-services</name>
        <value>mapreduce_shuffle</value>
    </property>
    <property>
        <name>yarn.nodemanager.env-whitelist</name>
                  <value>JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME</value>
    </property>

        <property>
                <name>yarn.scheduler.maximum-allocation-mb</name>
                <value>19000</value>
        </property>
<property>
        <name>yarn.nodemanager.resource.cpu-vcores</name>
        <value>16</value>
</property>
<property>
<name>yarn.nodemanager.resource.memory-mb</name>
<value>19000</value>
</property>
<property>
<name>yarn.scheduler.maximum-allocation-vcores</name>
<value>16</value>
</property>
        <!--Spark Yarn-->
    <!-- 是否开启聚合日志 -->
    <property>
        <name>yarn.log-aggregation-enable</name>
        <value>true</value>
    </property>
    <!-- 配置日志服务器的地址,work节点使用 -->
    <property>
        <name>yarn.log.server.url</name>
        <value>http://loaclhost:19888/jobhistory/logs/</value>
    </property>
    <!-- 配置日志过期时间,单位秒 -->
    <property>
        <name>yarn.log-aggregation.retain-seconds</name>
        <value>2592000</value>
    </property>
</configuration>
```
spark-defaults/conf

```
# Example:
spark.master                    yarn
spark.eventLog.enabled          true
spark.eventLog.compress         true
# 保存在hdfs上
spark.eventLog.dir  hdfs://localhost:9000/tmp/spark-yarn-logs
spark.history.fs.logDirectory hdfs://localhost:9000/tmp/spark-yarn-logs
spark.yarn.historyServer.address=localhost:18080
spark.history.ui.port=18080
```
I follow https://github.com/cubefs/compass/blob/main/docker/playground/README.md
Started compass
docker compose --profile compass up -d --build
But the Web UI : http://127.0.0.1:7075/compass is empty.
Is there any other config file I need to change?

**Comment by zebozhuang** [comment]
@liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?

**Comment by liewkaitsan** [comment]
> @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?
After I change the hostname or ip, do I need to change any configuration files?
Must have access to scheduling tools, I just want to implement spark task monitoring.

**Comment by liewkaitsan** [comment]
> @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?
can


> @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?

There was a problem with the layout, so I've changed it.

**Comment by liewkaitsan** [comment]
> @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?

There was a problem with the layout, so I've changed it.

**Comment by liewkaitsan** [comment]
> @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?
Can I add your wechat or qq?

**Comment by zebozhuang** [comment]
> > @liewkaitsan You can change local host to hostname or ip, usually we map ip to hostname in /etc/hosts. By the way , do you use scheduler?
> > Can I add your wechat or qq?

Yes, Please add wechat ID `zebozhuang`

**Comment by nilnon** [comment]
@liewkaitsan You can use the one click module to diagnose spark tasks.

**Comment by liewkaitsan** [comment]
> You can use the one click module to diagnose spark tasks

like this?
it's error
<img width="2297" alt="image" src="https://github.com/cubefs/compass/assets/48895152/0813a8f2-e4e6-4c8e-a86e-3c1d67f0372e">

<img width="1730" alt="image" src="https://github.com/cubefs/compass/assets/48895152/186963a9-78fe-4a1d-9718-8fb86a954673">

**Comment by nilnon** [comment]
@liewkaitsan yes, check whether the [application-hadoop.yml](https://github.com/cubefs/compass/blob/main/docker/playground/conf/application-hadoop.yml) configuration is correct, and check whether the task-metadata module is running.

**Comment by liewkaitsan** [comment]
> @liewkaitsan yes, check whether the [application-hadoop.yml](https://github.com/cubefs/compass/blob/main/docker/playground/conf/application-hadoop.yml) configuration is correct, and check whether the task-metadata module is running.

I'm not sure how these should be configured

yarn - clusterName I don't know where to configure this, I don't have yarn HA turned on.
hdfs uses a local pseudo-cluster, localhost:9000.
nameservices. I didn't set that up either

```
hadoop:
  namenodes:
    - nameservices: log-hdfs
      namenodesAddr: [ "localhost"]
      namenodes: [ "localhost" ]
      user: kaitsan
      password:
      port: 9000
      # scheduler platform hdfs log path keyword identification, used by task-application
      matchPathKeys: [ "flume" ]
      # kerberos
      enableKerberos: false
      # /etc/krb5.conf
      krb5Conf: ""
      # hdfs/*@EXAMPLE.COM
      principalPattern:  ""
      # admin
      loginUser: ""
      # /var/kerberos/krb5kdc/admin.keytab
      keytabPath: ""

  yarn:
    - clusterName: "bigdata"
      resourceManager: [ "localhost:8088" ]
      jobHistoryServer: "localhost:19888"

  spark:
    sparkHistoryServer: [ "localhost:18018" ]
```

**Comment by nilnon** [comment]
@liewkaitsan There is a problem with using localhost. It is best to change it to the hostname or IP. Yarn can also be used without turning on HA. ClusterName is optional.
