### ISSUE TITLE
[Question]: dataSkewGraphs sorting in spark DataSkewDetector

### ISSUE THREAD

**Issue by zhangkaixuan01** [cubefs/compass#197]
### What would you like to ask or discuss?

Why is the number of records used to judge data skew, but the number of bytes read is used for sorting?

**Comment by nilnon** [comment]
@zhangkaixuan01 Using records to sort is more rigorous. Are you interested in submitting a PR to optimize it?

**Comment by zhangkaixuan01** [comment]
> @zhangkaixuan01 Using records to sort is more rigorous. Are you interested in submitting a PR to optimize it?

Thanks for your reply, I've done it

**Comment by zebozhuang** [comment]
Solved by pr #198
