### ISSUE TITLE
[Question]: Calculation of the read rate in Spark HdfsStuckDetector

### ISSUE THREAD

**Issue by zhangkaixuan01** [cubefs/compass#199]
### What would you like to ask or discuss?

Why is the entire task time (task.getFinishTime() - task.getLaunchTime()) used as the denominator of the read rate calculation? It contains the task computing time

**Comment by nilnon** [comment]
The metric here is designed to look for tasks that are too slow to process data, so it includes the entire time, not just the rate at which it is read.

**Comment by zhangkaixuan01** [comment]
> The metric here is designed to look for tasks that are too slow to process data, so it includes the entire time, not just the rate at which it is read.

I still have questions, how can HDFS stuck be reflected?

**Comment by zebozhuang** [comment]
> > The metric here is designed to look for tasks that are too slow to process data, so it includes the entire time, not just the rate at which it is read.
> 
> I still have questions, how can HDFS stuck be reflected?

Sorry for the late reply, actually it's  a processing rate of task computing. if the rate is very low compared to threshold, that may cause stuck task, but that is not the absolute way for reflecting HDFS stuck.

**Comment by zhangkaixuan01** [comment]
> > > The metric here is designed to look for tasks that are too slow to process data, so it includes the entire time, not just the rate at which it is read.
> > 
> > 
> > I still have questions, how can HDFS stuck be reflected?
> 
> Sorry for the late reply, actually it's a processing rate of task computing. if the rate is very low compared to threshold, that may cause stuck task, but that is not the absolute way for reflecting HDFS stuck.

Okay, I understand now, thanks.
