### ISSUE TITLE
[Bug]: Error occur when startup for json parse error.

### ISSUE THREAD

**Issue by aib628** [cubefs/compass#203]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Current Behavior

When compass startup, JSONException happens and i see the error message attached below:

<img width="1509" alt="企业微信截图_bcd63b45-8371-45c5-87c1-aca71004c59f" src="https://github.com/cubefs/compass/assets/18046946/e8aac39c-0d80-4bbe-a40f-1a7a83f4261d">
<img width="1238" alt="企业微信截图_f8366fd3-613e-43e3-b14a-512cf3933847" src="https://github.com/cubefs/compass/assets/18046946/ba9a3574-1bf4-45b5-8a61-0352e7608740">

see source code at: task-metadata/src/main/java/com/oppo/cloud/meta/service/impl/ClusterConfigServiceImpl.java

### Expected Behavior

as we know, http://{yarn ip}/conf will response content format as xml, but there parse with json, so error occur

**Comment by nilnon** [comment]
@aib628 This is a known problem. Different versions of hadoop will return different formats. We will adapt to this problem. If you are interested, you can submit a PR and adapt according to responseEntity.getHeaders().get(HttpHeaders.CONTENT_TYPE).

**Comment by zebozhuang** [comment]
@aib628 fixed.

**Comment by aib628** [comment]
@zebozhuang so gelivable!

**Comment by aib628** [comment]
@zebozhuang I found some duplicate code in : com.oppo.cloud.flink.service.impl.ClusterConfigServiceImpl#getYarnPathInfo
You can fixed it together.

**Comment by packyan** [comment]
> @zebozhuang I found some duplicate code in : com.oppo.cloud.flink.service.impl.ClusterConfigServiceImpl#getYarnPathInfo
> 
> You can fixed it together.

PRs are welcomed. 😃

**Comment by aib628** [comment]
@packyan @zebozhuang I have adapt this fix to module task-flink, but clean code needed in the future.
Meanwhile, i have added support for variable attribute values to this feature, see detail at : 

![image](https://github.com/cubefs/compass/assets/18046946/49ec8131-40db-4384-a060-fa6f44bd59e3)
