### ISSUE TITLE
[Bug]: failed to start task-flink service

### ISSUE THREAD

**Issue by y1q84** [cubefs/compass#207]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Current Behavior

the services can't be start

### Compass Log

Field taskSyncerMetaService in com.oppo.cloud.flink.detect.TaskDetectScheduler required a single bean, but 2 were found:
        - applicationTaskExecutor: defined by method 'applicationTaskExecutor' in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class]
        - taskScheduler: defined by method 'taskScheduler' in class path resource [org/springframework/boot/autoconfigure/task/TaskSchedulingAutoConfiguration.class]

**Comment by zebozhuang** [comment]
> ### Contact Details
> _No response_
> 
> ### Is there an existing issue for this?
> * [x]  I have searched all the existing issues
> 
> ### Priority
> low (Default)
> 
> ### Current Behavior
> the services can't be start
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Compass Log
> Field taskSyncerMetaService in com.oppo.cloud.flink.detect.TaskDetectScheduler required a single bean, but 2 were found: - applicationTaskExecutor: defined by method 'applicationTaskExecutor' in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class] - taskScheduler: defined by method 'taskScheduler' in class path resource [org/springframework/boot/autoconfigure/task/TaskSchedulingAutoConfiguration.class]
> 
> ### Anything else? (Additional Context)
> _No response_

It seems duplicate beans are found. How did you start the flink service?

**Comment by zebozhuang** [comment]
@y1q84 We have found the bug, we will fix it.
