### ISSUE TITLE
Logic problem with checkLogPath judgment in HDFSUtil

### ISSUE THREAD

**Issue by yuehan-mm** [cubefs/compass#22]
**custom.rules.logPathJoins.data is**
```
hdfs://log-hdfs:8020/flume/airflow
```
**checkLogPath()**
```
private static String checkLogPath(NameNodeConf nameNode, String logPath) {
    // TODO return？
    if (logPath.split(":").length > 2) {
        return logPath;
    }
    return logPath.replace(nameNode.getNameservices(), nameNode.getNameservices() + ":" + nameNode.getPort());
}
```
-----
**may be we should change**
```
 if (logPath.split(":").length > 2) {
        return logPath;
 }
```
**to**
```
 if (logPath.split(":").length != 3) {
        return logPath;
 }
```
**or**
```
modify custom.rules.logPathJoins.data to remove 'hdfs:/'
```

**Comment by yuehan-mm** [comment]
link [https://github.com/cubefs/compass/issues/23](url)

**Comment by nilnon** [comment]
> hdfs://log-hdfs:8020/flume/airflow

@yuehan-mm The best practice should be that there is no need to add the port to the path, I will test it later.

**Comment by nilnon** [comment]
@yuehan-mm checkLogPath judgment is ok, whether or not the path contains ports, can you provide your error message?

**Comment by nilnon** [comment]
@yuehan-mm checkLogPath judgment is no problem, no matter the path contains ports, can you provide your error message?

**Comment by yuehan-mm** [comment]
@nilnon the mening of the current method  is to convert the base hdfs path to user’s hdfs path？
eg：convert hdfs://log-hdfs:8020/flume/airflow  to hdfs://mynameservice:8020/flume/airflow 
if so， the logic of current method is problematic.There are two issues.
1 it will be retrun in if block
2 [[https://github.com/cubefs/compass/issues/23](https://github.com/cubefs/compass/issues/url)](url)

**Comment by nilnon** [comment]
@yuehan-mm This method is to adapt whether the path contains ports, if the port is included, then return directly, otherwise add the port to the original path.

**Comment by yuehan-mm** [comment]
@nilnon i get it，but i still has some questions. our hdfs nameserver is configure in application-hadoop.yml.should we read the nameservice in  application-hadoop.yml and apply it in logPath？

**Comment by yuehan-mm** [comment]
@nilnon i understand what you mean，but what i mean is the ```rules.logPathJoins.data``` in application-airflow.yml is  ```hdfs://log-hdfs:8020/flume/airflow``` .  so the default nameservice is ```log-hdfs``` ,but our nameservice is configure in  ```application-hadoop.yml``` 
 . we should replace  ```log-hdfs```  by nameserver configure in application-hadoop.yml. but it does not seen to have been done.

i will supplement the log soon.

**Comment by yuehan-mm** [comment]
@nilnon i understand what you mean，but what i mean is the data.logPathJoins.data in application-airflow.yml is  ```hdfs://log-hdfs:8020/flume/airflow```  so the default nameservice is log-hdfs,but our nameservice is configure in  ```application-hadoop.yml``` 
 . we should replace  ```log-hdfs```  by nameserver configure in application-hadoop.yml. but it does not seen to have been done.


**i add log in code**
```
filePath = checkLogPath(nameNodeConf, filePath);
log.info("------filePath：" + filePath);
log.info("------nameservice：" + nameNodeConf.getNameservices());
FileSystem fs = HDFSUtil.getFileSystem(nameNodeConf);
FileStatus[] fileStatuses = fs.globStatus(new Path(filePath));
```
**log**

```
2023-04-13 16:31:55,407 INFO  131287 [delayed-queue-executor-2] [] : [com.oppo.cloud.application.util.HDFSUtil:136]------filePath：hdfs://log-hdfs:8020/flume/airflow/dag_id=JOB_COMPASS_HIVE_02/run_id=manual__2023-04-13T08_25_43_543139+00_00/task_id=COMPASS_HIVE_02/attempt=1*
2023-04-13 16:31:55,407 INFO  131287 [delayed-queue-executor-2] [] : [com.oppo.cloud.application.util.HDFSUtil:137] ------nameservice：nameservice1
```


when executing ```fs.globStatus(new Path(filePath));``` . an error will be report because is is an incorrect hdfs path.

**Comment by zebozhuang** [comment]
> > hdfs://log-hdfs:8020/flume/airflow
> 
> @yuehan-mm The best practice should be that there is no need to add the port to the path, I will test it later.

Yearh, good idea. The scheduler log should be uploaded to one hdfs cluster, that is the default hdfs path, after joining the namenode service name and task log path, it will be the real path.
