### ISSUE TITLE
[Question]: Flink task did not save metadata to opensearch?

### ISSUE THREAD

**Issue by fengjian1129** [cubefs/compass#222]
### What would you like to ask or discuss?

I want to analyze the usage of Flink tasks, but I see that I haven't saved Yarn information to Opensearch. Does Flink's real-time diagnostic function not support it？

![image](https://github.com/cubefs/compass/assets/35831367/141d815c-4a11-4ea2-876e-4461e25b3236)

**Comment by nilnon** [comment]
@fengjian1129 The task-metadata module already saves yarn information, and these duplicate codes should be removed.
