### ISSUE TITLE
[Bug]: Command `file` missing

### ISSUE THREAD

**Issue by xuchangqun** [cubefs/compass#223]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Current Behavior

When I install compass use docker, command `file` missing

### Compass Log

docker compose --profile compass up

compass  | plugin/
compass  | plugin/connector.rocketmq-1.1.6-jar-with-dependencies.jar
compass  | plugin/connector.pulsarmq-1.1.6-jar-with-dependencies.jar
compass  | plugin/connector.kafka-1.1.6-jar-with-dependencies.jar
compass  | plugin/connector.rabbitmq-1.1.6-jar-with-dependencies.jar
**compass  | bin/startup.sh: line 103: file: command not found**
compass  | cd to /opt/compass-v1.1.2/task-canal/bin for workaround relative path
compass  | LOG CONFIGURATION : /opt/compass-v1.1.2/task-canal/bin/../conf/logback.xml
compass  | canal conf : /opt/compass-v1.1.2/task-canal/bin/../conf/canal.properties

**Comment by nilnon** [comment]
The system installation may have reported an error. Add build parameters and try again. `docker compose --profile compass up--build`

**Comment by xuchangqun** [comment]
> The system installation may have reported an error. Add build parameters and try again. `docker compose --profile compass up --build`

I install the `file` command in the image.
Thx
