### ISSUE TITLE
replace problem with checkLogPath judgment in HDFSUtil

### ISSUE THREAD

**Issue by yuehan-mm** [cubefs/compass#23]
**checkLogPath()**

```
private static String checkLogPath(NameNodeConf nameNode, String logPath) {
    // TODO return？
    if (logPath.split(":").length > 2) {
        return logPath;
    }
    return logPath.replace(nameNode.getNameservices(), nameNode.getNameservices() + ":" + nameNode.getPort());
}
```
**base log path**
```logPath:hdfs://log-hdfs:8020/flume/airflow/dag_id=example_bash_operator/run_id=manual__2023-04-13T02_28_39_356311+00_00/task_id=runme_1/attempt=1```
**may be we should change**
```logPath.replace(nameNode.getNameservices(), nameNode.getNameservices() + ":" + nameNode.getPort());```
**to**
```logPath.replace("log-hdfs:8020", nameNode.getNameservices() + ":" + nameNode.getPort());```

**Comment by yuehan-mm** [comment]
link [https://github.com/cubefs/compass/issues/22](url)

**Comment by zebozhuang** [comment]
#22
