### ISSUE TITLE
cannot get project name from mysql

### ISSUE THREAD

**Issue by changfan2757** [cubefs/compass#27]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/41047139/232713395-872cdb93-31cb-42c2-bd75-9a3db7f796e7.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/41047139/232713519-22652590-a78f-43f4-9ab1-ebf28b96ddbf.png">

**Comment by nilnon** [comment]
@changfan2757 The problem has been fixed, please recompile tak-ui and then update, Thanks for your feedback.
