### ISSUE TITLE
Table field mapping exception

### ISSUE THREAD

**Issue by yuehan-mm** [cubefs/compass#31]
**in order to achieve data abstration in the scheduler layer.task-syncer has provides data mapping templates.but there seems to be some questions with the mapping between airflowDB.task_instance.try_number and comapssDB.task_instance.retry_times.**
```
airflowDB.task_instance.try_number： execute count
comapssDB.task_instance.retry_times：retry count
```

**try_number=1 is means execute once
retry_times=1  is means execute once ,retry once**

**Comment by nilnon** [comment]
@yuehan-mm We are already compatible with the airflow try_number problem, and the task-syncer mapping does not need to be modified, and we can be uniformly compatible in the program.
