### ISSUE TITLE
ElasticSearch query problem

### ISSUE THREAD

**Issue by yuehan-mm** [cubefs/compass#32]
the elasticSearch indeces of compass are  automatically created.The ElasticSearch string will be mapped to both text and keyword types by default.test and keyword are used in different query scenarios. compass used the wrong query.

**compass query log in task-detect**
```2023-04-28 14:53:36,538 INFO  657111 [delay-queue-executor-2] [] : [c.o.c.detect.service.impl.ElasticSearchServiceImp:151] indexes:[compass-job-instance-*], duration:0 ,condition:{"query":{"bool":{"filter":[{"terms":{"taskName":["TEST_TPCDS"],"boost":1.0}},{"terms":{"projectName":["SPARKSQL_TEST_20012523"],"boost":1.0}},{"terms":{"executionDate":["2023-04-28T01:29:58.000"],"boost":1.0}},{"terms":{"flowName":["SPARKSQL_TEST_20012523"],"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}```

**return empty list. when i change query condition to**
```{"query":{"bool":{"filter":[{"terms":{"executionDate":["2023-04-28T01:29:58.000"],"boost":1.0}},{"terms":{"taskName.keyword":["TEST_TPCDS"],"boost":1.0}},{"terms":{"projectName.keyword":["SPARKSQL_TEST_20012523"],"boost":1.0}},{"terms":{"flowName.keyword":["SPARKSQL_TEST_20012523"],"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}```

**it works**

may be we should change search condition or use elasticSearch index templete to close column mapping

**Comment by nilnon** [comment]
@yuehan-mm Thanks for your feedback, we have fixed this issue.
