### ISSUE TITLE
task-syncer模块同步task表update字段为空

### ISSUE THREAD

**Issue by wangyiji30** [cubefs/compass#38]
com.oppo.cloud.model.Task#setUpdateTime方法中
task.setCreateTime(DataUtil.parseDate(data.get("create_time")));
需要修改为
task.setUpdateTime(DataUtil.parseDate(data.get("update_time")));

**Comment by nilnon** [comment]
@wangyiji30 Thanks for your feedback, we have fixed this issue.

**Comment by zebozhuang** [comment]
fix.
