### ISSUE TITLE
Some continuous error logs in the text parser may not be captured

### ISSUE THREAD

**Issue by packyan** [cubefs/compass#45]
In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.

**Comment by zebozhuang** [comment]
> In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.

Thanks for your feedback,  we are integrating it now.

**Comment by packyan** [comment]
> > In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.
> 
> Thanks for your feedback, we are integrating it now.

In my test case, the second line will be considered as TAIL, even though it's a exception. But I am not sure this kind of log will be in real world or not :)

23/06/08 19:24:12 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Could not execute broadcast in 300 secs: java
23/06/08 19:24:34 INFO org.apache.spark.SparkException: Job aborted due to stage failure: File does not exist some info
23/06/08 19:24:55 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 9478 tasks (1024.1 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)

**Comment by zebozhuang** [comment]
> > > In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.
> > 
> > 
> > Thanks for your feedback, we are integrating it now.
> 
> In my test case, the second line will be considered as TAIL, even though it's a exception. But I am not sure this kind of log will be in real world or not :)
> 
> ```shell
> 23/06/08 19:24:12 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Could not execute broadcast in 300 secs: java
> 23/06/08 19:24:34 INFO org.apache.spark.SparkException: Job aborted due to stage failure: File does not exist some info
> 23/06/08 19:24:55 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 9478 tasks (1024.1 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)
> ```

OK, the case is a kind of action to parse 3 lines, did you write your own parsing rule? if so, please offer your rule or offer the rule you used which exists.

**Comment by packyan** [comment]
> > > > In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.
> > > 
> > > 
> > > Thanks for your feedback, we are integrating it now.
> > 
> > 
> > In my test case, the second line will be considered as TAIL, even though it's a exception. But I am not sure this kind of log will be in real world or not :)
> > ```shell
> > 23/06/08 19:24:12 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Could not execute broadcast in 300 secs: java
> > 23/06/08 19:24:34 INFO org.apache.spark.SparkException: Job aborted due to stage failure: File does not exist some info
> > 23/06/08 19:24:55 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 9478 tasks (1024.1 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)
> > ```
> 
> OK, the case is a kind of action to parse 3 lines, did you write your own parsing rule? if so, please offer your rule or offer the rule which exists.

I did not add any new rules, and by default, the above logs should be able to match the two sub-actions of jobFailedOrAbortedException: broadcastsTimeout and fileNotFoundException. However, in reality, the second line of the log was processed by the broadcastsTimeout action as TAIL, and was not matched by fileNotFoundException. It is normal that the third line of the log does not generate a result because there is no rule that matches it. By the way, if I add another line of log between the two lines, both exception logs can be matched by the action.

**Comment by zebozhuang** [comment]
> > > > > In com.oppo.cloud.common.util.textparser.TextParser#matchTailsTemplate, if there are multiple lines of continuous error logs, since the second line of logs is treated as TAIL, it cannot be captured as a ParserResult.
> > > > 
> > > > 
> > > > Thanks for your feedback, we are integrating it now.
> > > 
> > > 
> > > In my test case, the second line will be considered as TAIL, even though it's a exception. But I am not sure this kind of log will be in real world or not :)
> > > ```shell
> > > 23/06/08 19:24:12 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Could not execute broadcast in 300 secs: java
> > > 23/06/08 19:24:34 INFO org.apache.spark.SparkException: Job aborted due to stage failure: File does not exist some info
> > > 23/06/08 19:24:55 INFO org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 9478 tasks (1024.1 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)
> > > ```
> > 
> > 
> > OK, the case is a kind of action to parse 3 lines, did you write your own parsing rule? if so, please offer your rule or offer the rule which exists.
> 
> I did not add any new rules, and by default, the above logs should be able to match the two sub-actions of jobFailedOrAbortedException: broadcastsTimeout and fileNotFoundException. However, in reality, the second line of the log was processed by the broadcastsTimeout action as TAIL, and was not matched by fileNotFoundException. It is normal that the third line of the log does not generate a result because there is no rule that matches it. By the way, if I add another line of log between the two lines, both exception logs can be matched by the action.

Got it

**Comment by zebozhuang** [comment]
@packyan We have discovered there is a bug of the last line of the action, and your pull request takes no effect to handle this situation, we will fix it and enhance the textparser. Now you can change the rule by deleting the line: [https://github.com/cubefs/compass/blob/main/task-parser/src/main/resources/rules.json#L85](url), it will ignore tail of  this senario.
