### ISSUE TITLE
Flume配置问题

### ISSUE THREAD

**Issue by CinyuWen** [cubefs/compass#48]
在配置Flume采集海豚调度器日志到HDFS上时遇到以下问题：
1、海豚调度器的日志存放在以当日日期命名的YYYYMMDD动态文件夹内，Flume无法采集到动态文件夹内的日志，只能采集到一个静态日志文件夹内的日志文件
![微信图片_20230724155819](https://github.com/cubefs/compass/assets/88530508/230d5438-3a9f-438a-909c-08331e61365f)
日志路径如上图所示
2、在Flume上配置上传到HDFS文件前缀名为原文件名时，原文件名为带上全路径的文件名，导致上传到HDFS的文件多了很多目录级别，影响罗盘解析日志文件
比如某日志在原系统上的路径为/home/dolphinscheduler/dolphinscheduler/worker-server/logs/a.log
上传到HDFS上的路径会变成/flume/dolphinscheduler/home/dolphinscheduler/dolphinscheduler/worker-server/logs/a.log
而非/flume/dolphinscheduler/a.log
![微信截图_20230724162804](https://github.com/cubefs/compass/assets/88530508/23da554c-032e-4b22-8e5f-1766c9425719)
这是Flume的配置，请大佬指点一下这个配置方式有什么问题或者能不能提供一个Flume采集日志配置文件模板
谢谢大佬

**Comment by zebozhuang** [comment]
> 在配置Flume采集海豚调度器日志到HDFS上时遇到以下问题： 1、海豚调度器的日志存放在以当日日期命名的YYYYMMDD动态文件夹内，Flume无法采集到动态文件夹内的日志，只能采集到一个静态日志文件夹内的日志文件 ![微信图片_20230724155819](https://user-images.githubusercontent.com/88530508/255524486-230d5438-3a9f-438a-909c-08331e61365f.png) 日志路径如上图所示 2、在Flume上配置上传到HDFS文件前缀名为原文件名时，原文件名为带上全路径的文件名，导致上传到HDFS的文件多了很多目录级别，影响罗盘解析日志文件 比如某日志在原系统上的路径为/home/dolphinscheduler/dolphinscheduler/worker-server/logs/a.log 上传到HDFS上的路径会变成/flume/dolphinscheduler/home/dolphinscheduler/dolphinscheduler/worker-server/logs/a.log 而非/flume/dolphinscheduler/a.log `# Name the components on this agent agent01.sources = r2 agent01.sinks = k2 agent01.channels = c2
> 
> # Describe/configure the source
> agent01.sources.r2.type = spooldir agent01.sources.r2.spoolDir = /home/dolphinscheduler/dolphinscheduler/worker-server/logs/20230720 agent01.sources.r2.basenameHeader = true agent01.sources.r2.basenameHeaderKey = filename
> 
> # Describe the sink
> agent01.sinks.k2.type = hdfs agent01.sinks.k2.hdfs.path = hdfs://hadoop08:8020/flume/dolphinscheduler agent01.sinks.k2.hdfs.filePrefix = %{filename} agent01.sinks.k2.hdfs.fileType = DataStream agent01.sinks.k2.hdfs.batchsize = 130000 agent01.sinks.k2.hdfs.fileSuffix = .log #多久生成一个新的文件 agent01.sinks.k2.hdfs.rollInterval = 0 #设置每个文件的滚动大小 agent01.sinks.k2.hdfs.rolsize = 0 #文件的滚动与Event数量无关 agent01.sinks.k2.hdfs.rollCount = 0 agent01.channels.c2.type = memory agent01.sources.r2.channels = c2 agent01.sinks.k2.channel = c2` 这是Flume的配置，请大佬指点一下这个配置方式有什么问题或者能不能提供一个Flume采集日志配置文件模板 谢谢大佬

Thanks for your feedback. Here is our flume configuration file, please take it as an exmaple, it has to be modified according to your environment and flume code.

````properties
dolphin.sources = r1
dolphin.sinks = k1
dolphin.channels = c1
 
##################################################
# sources config
##################################################
dolphin.sources.r1.type = com.oppo.flume.plugin.source.taildir.TaildirRecursiveSource
dolphin.sources.r1.positionFile = /home/service/app/flume/tmp/taildir-position.json
dolphin.sources.r1.filegroups = f1
dolphin.sources.r1.filegroups.f1=/home/service/app/dolphinscheduler_201/logs/.*
dolphin.sources.r1.headers.f1.rootPath = /home/service/app/dolphinscheduler_201
dolphin.sources.r1.fileHeader = true
dolphin.sources.r1.interceptors = i1
dolphin.sources.r1.interceptors.i1.type = timestamp
dolphin.sources.r1.recursive = true
dolphin.sources.r1.cachePatternMatching = false 
#dolphin.sources.r1.ignoreOlder=1h
#dolphin.sources.r1.excludeFiles=dolphinscheduler-api|gc.log|dolphinscheduler-master|dolphinscheduler-worker


##################################################
# sinks config
##################################################
dolphin.sinks.k1.type = com.oppo.flume.plugin.sink.hdfs.HDFSWithPathSink
dolphin.sinks.k1.hdfs.path = hdfs://ansible-hdfs/flume/dolphinscheduler/%Y-%m-%d
dolphin.sinks.k1.hdfs.fileType = DataStream
dolphin.sinks.k1.hdfs.writeFormat=TEXT
dolphin.sinks.k1.hdfs.batchSize = 1000
dolphin.sinks.k1.hdfs.rollSize = 0 
dolphin.sinks.k1.hdfs.rollCount = 0
dolphin.sinks.k1.hdfs.rollInterval = 0
dolphin.sinks.k1.hdfs.idleTimeout = 5
dolphin.sinks.k1.hdfs.useLocalTimeStamp = true

##################################################
# channels config
##################################################
dolphin.channels.c1.type = memory
dolphin.channels.c1.capacity = 100000
dolphin.channels.c1.transactionCapacity = 10000

##################################################
# channel binder
##################################################
dolphin.sources.r1.channels = c1
dolphin.sinks.k1.channel = c1
````

**Comment by CinyuWen** [comment]
感谢大佬指点，不过好像你们是使用了自定义的flume source和sink组件，我想知道有没有什么快速的方法能帮助我部署好日志上传模块，从而使得罗盘能顺利地解析调度平台日志。谢谢

**Comment by zebozhuang** [comment]
> 感谢大佬指点，不过好像你们是使用了自定义的flume source和sink组件，我想知道有没有什么快速的方法能帮助我部署好日志上传模块，从而使得罗盘能顺利地解析调度平台日志。谢谢

ansible应该可以
