### ISSUE TITLE
The rule for determining abnormal CPU resource utilization seems not support the case of Spark tasks with DRA enabled

### ISSUE THREAD

**Issue by Kwafoor** [cubefs/compass#7]
In the case of Spark tasks with DRA(Spark Dynamic Resource Allocation) enabled, the calculated time is not equivalent to `totalCores * appTotalTime`.
```java
long maxExecutors = getMaxConcurrent();
long executorCores = Long.parseLong(application.getSparkExecutorCores());
long totalCores = executorCores * maxExecutors;

long appComputeMillisAvailable = totalCores * appTotalTime;
long inJobComputeMillisAvailable = totalCores * jobTime;
```

**Comment by wForget** [comment]
Also, is there a problem with the judgment here?

https://github.com/cubefs/compass/blob/d2457b24c460a2cbd343cb318cf8a28b9ee5a4dc/task-parser/src/main/java/com/oppo/cloud/parser/service/job/detector/CpuWasteDetector.java#L99

**Comment by zebozhuang** [comment]
> Also, is there a problem with the judgment here?
> 
> https://github.com/cubefs/compass/blob/d2457b24c460a2cbd343cb318cf8a28b9ee5a4dc/task-parser/src/main/java/com/oppo/cloud/parser/service/job/detector/CpuWasteDetector.java#L99

@wForget Thanks for your feedback, please check it in the latest version.

**Comment by zebozhuang** [comment]
> In the case of Spark tasks with DRA(Spark Dynamic Resource Allocation) enabled, the calculated time is not equivalent to `totalCores * appTotalTime`.
> 
> ```java
> long maxExecutors = getMaxConcurrent();
> long executorCores = Long.parseLong(application.getSparkExecutorCores());
> long totalCores = executorCores * maxExecutors;
> 
> long appComputeMillisAvailable = totalCores * appTotalTime;
> long inJobComputeMillisAvailable = totalCores * jobTime;
> ```
@Kwafoor Thanks for you feedback, the CPU resource Utilization is a estimation, we find that result `appComputeMillisAvailable ` of the algorithm is always  smaller than the resource usage of yarn container,
and we set a higher  threshold for this utilization to make sure the algorithm can diagnose Spark application efficiently. Next we will do more research on it to improve the algorithm.

**Comment by Kwafoor** [comment]
> > In the case of Spark tasks with DRA(Spark Dynamic Resource Allocation) enabled, the calculated time is not equivalent to `totalCores * appTotalTime`.
> > ```java
> > long maxExecutors = getMaxConcurrent();
> > long executorCores = Long.parseLong(application.getSparkExecutorCores());
> > long totalCores = executorCores * maxExecutors;
> > 
> > long appComputeMillisAvailable = totalCores * appTotalTime;
> > long inJobComputeMillisAvailable = totalCores * jobTime;
> > ```
> 
> @Kwafoor Thanks for you feedback, the CPU resource Utilization is a estimation, we find that result `appComputeMillisAvailable ` of the algorithm is always smaller than the resource usage of yarn container, and we set a higher threshold for this utilization to make sure the algorithm can diagnose Spark application efficiently. Next we will do more research on it to improve the algorithm.

Thank you for your reply. I am very interested in this and hope to submit a patch later to improve these issues. I will close this now.
