### ISSUE TITLE
Exception details are ignored

### ISSUE THREAD

**Issue by wForget** [cubefs/compass#8]
When I start the task-portal service and open the ui page I get an error and there are no error infos in the service log. I guess the error is due to no data in elasticsearch.

error api: /compass/api/v1/job/graph
response: {"code":500,"msg":null,"data":null}

We can remove the try-catch in the controllers, and the error will be caught and handled by exceptionHandler in `GlobalExceptionConfig` and record the error log.

**Comment by hoey94** [comment]
I am trying to initialize the INDEX of ES to prevent further errors, like this:
```shell
PUT /compass-yarn-app
put /compass-spark-app
put /compass-job-analysis
put /compass-task-app
put /compass-job-instance

PUT /compass-yarn-app-
put /compass-spark-app-
put /compass-job-analysis-
put /compass-task-app-
put /compass-job-instance-
```
Has the author neglected to upload the initialization script for ES?

**Comment by wForget** [comment]
> Has the author neglected to upload the initialization script for ES?

This may not be necessary, as other modules start and the index will be created automatically when es data is written.

**Comment by nilnon** [comment]
> When I start the task-portal service and open the ui page I get an error and there are no error infos in the service log. I guess the error is due to no data in elasticsearch.
> 
> error api: /compass/api/v1/job/graph response: {"code":500,"msg":null,"data":null}
> 
> We can remove the try-catch in the controllers, and the error will be caught and handled by exceptionHandler in `GlobalExceptionConfig` and record the error log.

@wForget Thanks for your feedback, we will optimize this issue later.

**Comment by nilnon** [comment]
> > Has the author neglected to upload the initialization script for ES?
> 
> This may not be necessary, as other modules start and the index will be created automatically when es data is written.

@hoey94 @wForget Yes, there is no need to manually create indexes.
