### ISSUE TITLE
GC Analyse memory usage by the tool gcviewer is replaced by gctoolkit

### ISSUE THREAD

**Issue by nilnon** [cubefs/compass#94]
GCViewer's license is LGPL, is not compatile with Apache 2.0, will be replaced by gctoolkit.

**Comment by zebozhuang** [comment]
Yes, LGPL license is more strict than Apache 2.0
| |
zhuangzebo
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/14/2023 14:40 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [cubefs/compass] GC Analyse memory usage by the tool gcviews replaced by gctoolkit (Issue #94) |
