### ISSUE TITLE
StageDurationDetector耗时异常stageDuration的逻辑确定

### ISSUE THREAD

**Issue by ketingli1** [cubefs/compass#97]
long stageDuration = completeTime - firstLaunchTime;
现逻辑为stage的completeTime减去第一个开始运行task的firstLaunchTime

为什么不用stageDuration = submissionTime - firstLaunchTime;
submissionTime才是stage真实开始运行的时间

**Comment by zebozhuang** [comment]
submissionTime是提交，开始时间，这样stage运行时间没包含在内，我们需要确认下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月15日 11:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [cubefs/compass] StageDurationDetector耗时异常stageDuration的逻辑确定 (Issue #97) |

long stageDuration = completeTime - firstLaunchTime;
现逻辑为stage的completeTime减去第一个开始运行task的firstLaunchTime

为什么不用stageDuration = submissionTime - firstLaunchTime;
submissionTime才是stage真实开始运行的时间

**Comment by ketingli1** [comment]
sorry，我写错，为什么不用stageDuration = completeTime - submissionTime;
作为stage耗时异常的总时间

**Comment by nilnon** [comment]
@ketingli1 

- [https://issues.apache.org/jira/browse/SPARK-10930](https://issues.apache.org/jira/browse/SPARK-10930)
- [https://github.com/apache/spark/pull/9051](https://github.com/apache/spark/pull/9051)
- [https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/jobs/StageTable.scala#L307](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/jobs/StageTable.scala#L307)

可以参考以上链接，Spark源码计算stage durtaion如下
```
    val finishTime = stageData.completionTime.map(_.getTime()).getOrElse(currentTime)

    // The submission time for a stage is misleading because it counts the time
    // the stage waits to be launched. (SPARK-10930)
    val duration = stageData.firstTaskLaunchedTime.map { date =>
      val time = date.getTime()
      if (finishTime > time) {
        finishTime - time
      } else {
        None
        currentTime - time
      }
    }
```
